### ISSUE TITLE
fix:  I tried “Generate a New Wallet” first, then exited out after some testing, then tried to click “Add an Existing Wallet” and I got no feedback.  Had to refresh to get it to work again.

### ISSUE THREAD

**Issue by jojobyte** [dashhive/wallet-ui#23]

**Comment by riongull** [comment]
A new issue was introduced with the fix.  Creating a new wallet doesn't work anymore.  I'm guess that's a simple fix.  Please fix that and I'll try again to reproduce the original issue.

**Comment by jojobyte** [comment]
@riongull generating a new wallet should work now. 9420124d38e2d428c9ceb6c1caf7d990923a8f7b

**Comment by riongull** [comment]
Works now.  This issue seems resolved.
