### ISSUE TITLE
Keystore / Seed Phrase field enhancements

### ISSUE THREAD

**Issue by jojobyte** [dashhive/wallet-ui#36]
style: After I’ve picked a file (or dropped one into the field) I want the “Seed Phrase” field to go away since it will never be needed in that case, and the user shouldn’t feel like he’s leaving something blank.

If I’ve picked a “backup” then the alias should go away also, since it is always required when making a new wallet (is it enforced when backing up?).

If so, it would be populated after hitting “Add wallet” and the user can always edit it, but I don’t think we should help them get in the habit of redefining the alias here in the “Existing Wallet” import.

An alternative to hiding the alias field would be to name it automatically by the file name, but that might require more coding than it’s worth, and it might clash with the name in the keystore file, so I’m not sure that’s a good option.

**Comment by jojobyte** [comment]
@riongull per this commit 5afad8a47c2b980e68c9585d44c2a4a87980a2cd, there should be enhancements to the original stage 1 functionality.

Keystore drop zone or seed phrase field should get disabled based on interaction with the opposing field.

Alias has updates for Generate & Import to have better descriptions & a title set that gets displayed when the forms pattern is invalid, and details how to make a valid alias.

Please check https://fix-stage-1-qa.wallet.dashincubator.dev/ and see if that matches your expectations.

**Comment by riongull** [comment]
Disabling the unnecessary fields is a nice improvement.  I think I'm still inclined to disable the populated alias field as well, but maybe let's have @coolaj86 and/or others test it to see what they have to say.   

A couple issues:

- [ ] There's no way to unselect an already selected file
- [ ] The file upload field doesn't highlight when tabbing.  it works, just no visual feedback.

**Comment by jojobyte** [comment]
> * [x]  The file upload field doesn't highlight when tabbing.  it works, just no visual feedback.

Should be fixed by 4cc1303e568602c7948aa076e4b7a9b7fd809516

**Comment by jojobyte** [comment]
> * [x]  There's no way to unselect an already selected file

Should be fixed by 46ce8ccda5c9845b7881e3e752ceb173bda1b515
