### ISSUE TITLE
QR code to fund my own wallet in the Receive modal

### ISSUE THREAD

**Issue by riongull** [dashhive/wallet-ui#38]
I need a quick and easy way to fund my own wallet. Usually it’s right there available when a user hits “Receive” in his wallet. I think that’s probably the most intuitive place due to people being use to it in other wallets. Currently we have that feature under MyAlias > Edit Profile. I don’t think that’s the right place for it.

**Comment by jojobyte** [comment]
> I need a quick and easy way to fund my own wallet. Usually it’s right there available when a user hits “Receive” in his wallet. I think that’s probably the most intuitive place due to people being use to it in other wallets. Currently we have that feature under MyAlias > Edit Profile. I don’t think that’s the right place for it.

Right now, you can select `Receive` and then in the dialog that pops up, press the `Receive` button and fund your wallet.

Is the issue that it doesn't specifically say "Fund your wallet"?

**Comment by riongull** [comment]
The issue is that most people are accustomed to seeing a QR code right when they click receive.  

I'm not sure what the best solution is, since we're trying to promote contacts, but what we have isn't easy/intuitive enough. I'll give it some thought.

**Comment by jojobyte** [comment]
Should be fixed by 825d3c269e2fd5b339d0a75fd8bcc29ef2efa97d
