### ISSUE TITLE
Payment QR/URI Share Flow Improvements

### ISSUE THREAD

**Issue by jojobyte** [dashhive/wallet-ui#50]
We already changed the order of the dialogs that display when clicking the `Receive` button on the main page, however improvements could be made so that if you select a contact and/or enter an amount, those values are remembered and auto-filled if you decide to "select a contact" again.

- Need to display contacts alias if one is selected for the QR
- Fix: Amount is not currently cleared after closing the Receive QR Dialog.

**Comment by jojobyte** [comment]
@riongull please review this feature/functionality at https://fix-dashwallet-implementation.wallet.dashincubator.dev/ and change Status to Done if you approve or back to "In Progress" if it needs more work.

**Comment by riongull** [comment]
On the "Share to receive funds" dialog, maybe change the "Select a Contact" button to "Edit Receive Details" or "Edit Amount or Contact" or something like that?

I'm not sure I love the UX, but it's good enough for now for sure.  I'll re-open this or make a new issue later after I've used it more in the real world more.  Everything seems to work as intended, so go ahead and close this after you've changed that button text, or at least considered it (if you have a good reason to leave it that's okay with me).

**Comment by jojobyte** [comment]
> On the "Share to receive funds" dialog, maybe change the "Select a Contact" button to "Edit Receive Details" or "Edit Amount or Contact" or something like that?

Should be updated now at https://feat-surface-errors.wallet.dashincubator.dev/

Setting this issues status to done.
